#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <string>

static const std::string  soapControlDescription = 

"<?xml version=\"1.0\"?>"
"<scpd>" //  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"<specVersion>"
"<major>1</major>"
"<minor>0</minor>"
"</specVersion>"
""
"<actionList>"

		/*

"<action>"
"  <name>GetVersion</name>"
"  <argumentList>"
"	 <argument>"
"      <name>Version</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>GetHostname</name>"
"  <argumentList>"
"	 <argument>"
"      <name>Hostname</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>GetUptime</name>"
"  <argumentList>"
"	 <argument>"
"      <name>Uptime</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

*/

"<action>"
"  <name>GetSystemInfo</name>"
"  <argumentList>"
"    <argument>"
"      <name>SystemInfo</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_SystemInfoValue</relatedStateVariable>"
"    </argument>"
"	 <argument>"
"      <name>Result</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>GetSystemPath</name>"
"  <argumentList>"
"    <argument>"
"      <name>SystemPath</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_SystemPathValue</relatedStateVariable>"
"    </argument>"
"	 <argument>"
"      <name>Result</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"    <argument>"
"      <name>Description</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"






/** PROFILER */

"<action>"
"  <name>GetSessionProfiles</name>"
"  <argumentList>"
"	 <argument>"
"      <name>Result</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>GetSessionProfile</name>"
"  <argumentList>"
"	 <argument>"
"      <name>ProfileID</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_ProfileID</relatedStateVariable>"
"    </argument>"
"	 <argument>"
"      <name>Result</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"


/** CONFIGURATION */
"<action>"
"  <name>GetConfigFileName</name>"
"  <argumentList>"
"    <argument>"
"      <name>ConfigFileName</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>GetInterface</name>"
"  <argumentList>"
"    <argument>"
"      <name>Interface</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>SetInterface</name>"
"  <argumentList>"
"    <argument>"
"      <name>Interface</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"    <argument>"
"      <name>Result</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>GetHttpPort</name>"
"  <argumentList>"
"    <argument>"
"      <name>HttpPort</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_NumberValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>SetHttpPort</name>"
"  <argumentList>"
"    <argument>"
"      <name>HttpPort</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_NumberValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"


"<action>"
"  <name>GetCharset</name>"
"  <argumentList>"
"    <argument>"
"      <name>Charset</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>SetCharset</name>"
"  <argumentList>"
"    <argument>"
"      <name>Charset</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"


"<action>"
"  <name>GetTempDir</name>"
"  <argumentList>"
"    <argument>"
"      <name>TempDir</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>SetTempDir</name>"
"  <argumentList>"
"    <argument>"
"      <name>TempDir</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"    <argument>"
"      <name>Result</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"


"<action>"
"  <name>GetUuid</name>"
"  <argumentList>"
"    <argument>"
"      <name>Uuid</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>SetUuid</name>"
"  <argumentList>"
"    <argument>"
"      <name>Uuid</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"


"<action>"
"  <name>GetIsFixedUuid</name>"
"  <argumentList>"
"    <argument>"
"      <name>IsFixedUuid</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_BoolValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>SetIsFixedUuid</name>"
"  <argumentList>"
"    <argument>"
"      <name>IsFixedUuid</name>"
"      <direction>in</direction>"
"      <relatedStateVariable>A_ARG_TYPE_BoolValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"




/** DATABASE */

"<action>"
"  <name>GetDatabaseStatus</name>"
"  <argumentList>"
"    <argument>"
"      <name>DatabaseStatus</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>DatabaseRebuild</name>"
"  <argumentList>"
"    <argument>"
"      <name>DatabaseStatus</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"

"<action>"
"  <name>DatabaseUpdate</name>"
"  <argumentList>"
"    <argument>"
"      <name>DatabaseStatus</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"



"<action>"
"  <name>GetVirtualContainers</name>"
"  <argumentList>"
"    <argument>"
"      <name>VirtualContainers</name>"
"      <direction>out</direction>"
"      <relatedStateVariable>A_ARG_TYPE_StringValue</relatedStateVariable>"
"    </argument>"
"  </argumentList>"
"</action>"





/*
"	<action>"
"<name>GetSortCapabilities</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>SortCaps</name>"
"<direction>out</direction>"
"<relatedStateVariable>SortCapabilities</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"	<action>"
"<name>GetSystemUpdateID</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>Id</name>"
"<direction>out</direction>"
"<relatedStateVariable>SystemUpdateID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"	<action>"
"<name>Browse</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>ObjectID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>BrowseFlag</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_BrowseFlag</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>Filter</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_Filter</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>StartingIndex</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_Index</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>RequestedCount</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>SortCriteria</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_SortCriteria</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>Result</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>NumberReturned</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>TotalMatches</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>UpdateID</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_UpdateID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"	<action>"
"<name>Search</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>ContainerID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>SearchCriteria</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_SearchCriteria</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>Filter</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_Filter</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>StartingIndex</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_Index</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>RequestedCount</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>SortCriteria</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_SortCriteria</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>Result</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>NumberReturned</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>TotalMatches</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>UpdateID</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_UpdateID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"<action>"
"<name>CreateObject</name>"
"<argumentList>"
"<argument>"
"<name>ContainerID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
"<argument>"
"<name>Elements</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"</argument>"
"<argument>"
"<name>ObjectID</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
"<argument>"
"<name>Result</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"<action>"
"<name>DestroyObject</name>"
"<argumentList>"
"<argument>"
"<name>ObjectID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"<action>"
"<name>UpdateObject</name>"
"<argumentList>"
"<argument>"
"<name>ObjectID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
"<argument>"
"<name>CurrentTagValue</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_TagValueList</relatedStateVariable>"
"</argument>"
"<argument>"
"<name>NewTagValue</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_TagValueList</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"<action>"
"<name>ImportResource</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>SourceURI</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_URI</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>DestinationURI</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_URI</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>TransferID</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_TransferID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"	<action>"
"<name>ExportResource</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>SourceURI</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_URI</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>DestinationURI</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_URI</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>TransferID</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_TransferID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"	<action>"
"<name>StopTransferResource</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>TransferID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_TransferID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"	<action>"
"<name>GetTransferProgress</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>TransferID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_TransferID</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>TransferStatus</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_TransferStatus</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>TransferLength</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_TransferLength</relatedStateVariable>"
"</argument>"
""
"	<argument>"
"<name>TransferTotal</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_TransferTotal</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"	<action>"
"<name>DeleteResource</name>"
""
"	<argumentList>"
""
"	<argument>"
"<name>ResourceURI</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_URI</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
""
"<action>"
"<name>CreateReference</name>"
"<argumentList>"
"<argument>"
"<name>ContainerID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
"<argument>"
"<name>ObjectID</name>"
"<direction>in</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
"<argument>"
"<name>NewID</name>"
"<direction>out</direction>"
"<relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"</argument>"
"</argumentList>"
"</action>"
*/

"</actionList>"

"<serviceStateTable>"

"  <stateVariable sendEvents=\"no\">"
"    <name>A_ARG_TYPE_StringValue</name>"
"    <dataType>string</dataType>"
"  </stateVariable>"
""
"  <stateVariable sendEvents=\"no\">"
"    <name>A_ARG_TYPE_ProfileID</name>"
"    <dataType>string</dataType>"
"  </stateVariable>"
""
"  <stateVariable sendEvents=\"no\">"
"    <name>A_ARG_TYPE_Result</name>"
"    <dataType>string</dataType>"
"  </stateVariable>"
""
"  <stateVariable sendEvents=\"no\">"
"    <name>A_ARG_TYPE_NumberValue</name>"
"    <dataType>ui4</dataType>"
"  </stateVariable>"
""
"  <stateVariable sendEvents=\"no\">"
"    <name>A_ARG_TYPE_BoolValue</name>"
"    <dataType>string</dataType>"
"    <allowedValueList>"
"      <allowedValue>true</allowedValue>"
"      <allowedValue>false</allowedValue>"
"    </allowedValueList>"
"  </stateVariable>"
""
"  <stateVariable sendEvents=\"no\">"
"    <name>A_ARG_TYPE_SystemInfoValue</name>"
"    <dataType>string</dataType>"
"    <allowedValueList>"
"      <allowedValue>Version</allowedValue>"
"      <allowedValue>Hostname</allowedValue>"
"      <allowedValue>Uptime</allowedValue>"
"    </allowedValueList>"
"  </stateVariable>"
""
"  <stateVariable sendEvents=\"no\">"
"    <name>A_ARG_TYPE_SystemPathValue</name>"
"    <dataType>string</dataType>"
"    <allowedValueList>"
"      <allowedValue>Configuration</allowedValue>"
"      <allowedValue>Devices</allowedValue>"
"      <allowedValue>Vfolders</allowedValue>"
"      <allowedValue>Plugins</allowedValue>"
"      <allowedValue>Data</allowedValue>"
"      <allowedValue>Thumbnails</allowedValue>"
"    </allowedValueList>"
"  </stateVariable>"
""



/*
""
"	<stateVariable sendEvents=\"yes\">"
"<name>TransferIDs</name>"
"<dataType>string</dataType>"
"</stateVariable>"
     ""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_SearchCriteria</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_BrowseFlag</name>"
"<dataType>string</dataType>"
""
"	<allowedValueList>"
"<allowedValue>BrowseMetadata</allowedValue>"
"<allowedValue>BrowseDirectChildren</allowedValue>"
"</allowedValueList>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_Filter</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_SortCriteria</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_Index</name>"
"<dataType>ui4</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_Count</name>"
"<dataType>ui4</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_UpdateID</name>"
"<dataType>ui4</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_TransferID</name>"
"<dataType>ui4</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_TransferStatus</name>"
"<dataType>string</dataType>"
""
"	<allowedValueList>"
"<allowedValue>COMPLETED</allowedValue>"
"<allowedValue>ERROR</allowedValue>"
"<allowedValue>IN_PROGRESS</allowedValue>"
"<allowedValue>STOPPED</allowedValue>"
"</allowedValueList>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_TransferLength</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_TransferTotal</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_TagValueList</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>A_ARG_TYPE_URI</name>"
"<dataType>uri</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>SearchCapabilities</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"no\">"
"<name>SortCapabilities</name>"
"<dataType>string</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"yes\">"
"<name>SystemUpdateID</name>"
"<dataType>ui4</dataType>"
"</stateVariable>"
""
"	<stateVariable sendEvents=\"yes\">"
"<name>ContainerUpdateIDs</name>"
"<dataType>string</dataType>"
"</stateVariable>"
*/

"</serviceStateTable>"
"</scpd>";
